### ISSUE TITLE
properly handle error when request fails

### ISSUE THREAD

**Issue by albertalquisola** [scott-wyatt/node-mozscape#4]
```
function cb(error, response, body) {

      if (!error && response.statusCode > 200) {
        callback({status: response.statusCode, msg: body});
      } else {
        callback(null, JSON.parse(body));
      }
    }
```

when moz is down/not responding, an error is returned. The error here though isnt handled and a runtime error occurs on JSON.parse(body) because body is undefined.

**Comment by albertalquisola** [comment]
submitted a PR fix for this
https://github.com/scott-wyatt/node-mozscape/pull/5

**Comment by scott-wyatt** [comment]
Merged.
